### ISSUE TITLE
Add more directives for ignoring

### ISSUE THREAD

**Issue by davidosomething** [fdecampredon/istanbulify#2]
E.g. read package.json for
"istanbulify": {
  "ignore": {
    './somepath'
  }
}

or make compatible with the popular browserify-shim transform

Right now if you bundle externals they get covered

**Comment by ivanoats** [comment]
:+1: this would be useful to ignore code from bower packages

**Comment by chandru9279** [comment]
@davidosomething and @ivanoats 

For better ignores, you can use this. Simply create a js file and put the following snippet :

```
var brist = require('browserify-istanbul');
console.log("configured coverage module loaded")
module.exports = brist({
    // https://github.com/isaacs/minimatch - ['**Web.JasmineTests**'] will not work. ** is treated differently in paths
    ignore: ['**/Web.JasmineTests/**'],

    // Ignores ['**/node_modules/**', '**/test/**', '**/tests/**']
    defaultIgnore: true
})
```

Now in your browserify `transform: []` list, give the full string path to this module. Of course you  need to npm-install browserify-istanbul
